# Generated by Django 4.0.2 on 2022-02-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfp', '0001_initial'),
    ]

    operations = [
    ]
